name: demo.playwright.pwc-failed
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  basicFailedTests:
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the job in parallel
        shard: [1, 2, 3]

    name: "Playwright Tests - pwc - failed"
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # https://github.com/actions/runner-images/issues/6775
      - run: |
          echo "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chrome
          npx playwright install

      - name: Run Test
        continue-on-error: false
        working-directory: ./basic
        env:
          CURRENTS_API_URL: https://cy-staging.currents.dev
          CURRENTS_PROJECT_ID: kTvs8s
          CURRENTS_RECORD_KEY: ${{ secrets.STAGING_CURRENTS_RECORD_KEY }}
          CURRENTS_CI_BUILD_ID: reporter-${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}
        run: |
          npx pwc --shard=${{ matrix.shard }}/${{ strategy.job-total }} --reporter blob

      - name: Upload reports as artifacts.
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blobReports-${{ matrix.shard }}
          path: |
            blob-report
